version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mazin123
      MYSQL_DATABASE: ecommerce_database
    networks:
      - my-network

  redis:
    image: redis
    restart: always
    networks:
      - my-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: always
    environment:
      - discovery.type=single-node
    networks:
      - my-network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis
      - elasticsearch
    networks:
      - my-network

networks:
  my-network:

