version: '3'
services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/mysql
      

  redis:
    image: redis
    restart: always
    container_name: redis


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
   
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis
      - elasticsearch
volumes:
  data:

