version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mazin123
      MYSQL_DATABASE: ecommerce_database
      MYSQL_USER: mazzon
      MYSQL_PASSWORD: mazzon123
    volumes:
      - data:/var/lib/mysql
      

  redis:
    image: redis
    restart: always


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: always
    environment:
      - discovery.type=single-node
   
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis
      - elasticsearch
volumes:
  data:

