# Generated by Django 4.2.1 on 2023-12-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWeb', '0003_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
