# Generated by Django 4.2.1 on 2023-12-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWeb', '0005_order_is_deleted_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sequance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sequance',
            field=models.IntegerField(default=100),
        ),
    ]
