# Generated by Django 4.2.1 on 2023-12-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoWeb', '0006_category_sequance_product_sequance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sequance',
            new_name='sequence',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sequance',
            new_name='sequence',
        ),
    ]
